# fly.toml app configuration file generated for oceanlandmining on 2023-06-07T23:21:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oceanlandmining"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
